var pin = 411014;
var city = "pune";
var is_in_maharashtra=true;
console.log(pin, typeof pin);
console.log(city, typeof city);
console.log(is_in_maharashtra, typeof is_in_maharashtra);
console.log("=======================");
var difference;
console.log(typeof difference);
var difference=null;
console.log(typeof difference);
